# Generated by Django 5.2.4 on 2025-07-17 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0003_alter_song_album'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, default='default-album-img.svg', null=True, upload_to='images/%Y/%m/%d/'),
        ),
    ]
