# Generated by Django 5.2.4 on 2025-07-17 09:14

import songs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0004_alter_song_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='song',
            name='image',
            field=models.ImageField(blank=True, default='default-album-img.svg', null=True, upload_to=songs.models.image_upload_path),
        ),
    ]
