# Generated by Django 5.2.4 on 2025-07-17 09:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('songs', '0005_alter_song_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='url',
        ),
    ]
