# Generated by Django 5.2.4 on 2025-07-24 08:26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("songs", "0006_remove_song_url"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="song",
            name="total_likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="song",
            index=models.Index(
                fields=["-total_likes"], name="songs_song_total_l_6bbc80_idx"
            ),
        ),
    ]
